AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'db/schema.rb'
    # - 'config/**/*'
    # - 'script/**/*'
Rails:
  Enabled: true
# Style/Documentation:
#   Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 5
Style/ClassAndModuleChildren:
  Enabled: false
# Frozen String Literal Pragma will not be needed in Ruby 3+ as it will be the
# default, Added `frozen_string_literal: true` to use this new default
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
