language: ruby
rvm:
  - 1.9.3
  - 1.9.3-p385
  - 2.0.0
before_script:
  - "ruby lib/initial_setup.rb ../.travis_setup"
  - "psql -c 'create database slice_test;' -U postgres"
  - "bundle exec rake db:migrate"
matrix:
  allow_failures:
    - rvm: 1.9.3-p385
