sudo: false
language: ruby
rvm:
  - 2.2.3
  - 2.3.0-preview1
before_script:
  - "ruby lib/initial_setup.rb ../.travis_setup"
  - "psql -c 'create database slice_test;' -U postgres"
  - "bundle exec rake db:migrate"
matrix:
  allow_failures:
    - rvm: 2.3.0-preview1
