language: ruby
rvm:
- 2.6.1
- ruby-head
gemfile: "gems.rb"
before_script:
- "ruby lib/initial_setup.rb ../.travis_setup"
- "psql -c 'create database slice_test;' -U postgres"
- "rails db:migrate"
matrix:
  allow_failures:
  - rvm: ruby-head
