language: ruby
rvm:
  - 1.9.3
  - 2.0.0
before_script:
  - "ruby lib/initial_setup.rb ../.travis_setup"
  - "psql -c 'create database slice_test;' -U postgres"
  - "gem install bundler --pre"
  - "bundle exec rake db:migrate"
